### ISSUE TITLE
Certificate signed by unknown authority

### ISSUE THREAD

**Issue by thomas-illiet** [mtulio/rundeck-exporter#4]
Hello @mtulio :)

Can you add SSL support and add support for SSL Bypass?

```shell
azion_1  | panic: Get https://xxxxxx/metrics/metrics/metrics/metrics?pretty=true: x509: certificate signed by unknown authority
azion_1  |
azion_1  | goroutine 1 [running]:
azion_1  | github.com/mtulio/rundeck-exporter/src/rclient.(*RClient).UpdateMetrics(0xc000085540, 0xc0000c99c0, 0x4130d2)
azion_1  |      /home/marcobraga/.go/src/github.com/mtulio/rundeck-exporter/src/rclient/metrics.go:42 +0xdf
azion_1  | github.com/mtulio/rundeck-exporter/src/collector.(*RMetrics).InitMetrics(0xc00006db60, 0x0, 0x0, 0x0, 0x40cb9d, 0x8ba340)
azion_1  |      /home/marcobraga/.go/src/github.com/mtulio/rundeck-exporter/src/collector/metrics.go:58 +0x11c7
azion_1  | github.com/mtulio/rundeck-exporter/src/collector.NewCollectorMetrics(0xc000085540, 0x3c, 0x0, 0x0, 0x0, 0x0, 0xc0000c9e40, 0x40bfc8)
azion_1  |      /home/marcobraga/.go/src/github.com/mtulio/rundeck-exporter/src/collector/metrics.go:46 +0x80
azion_1  | github.com/mtulio/rundeck-exporter/src/collector.NewCollectorMaster(0xc000085540, 0x3c, 0x1, 0xc000069590, 0xc0000c9ea0)
azion_1  |      /home/marcobraga/.go/src/github.com/mtulio/rundeck-exporter/src/collector/master.go:52 +0x58
azion_1  | main.initPromCollector(0xc0000c9f48, 0xc000085540)
azion_1  |      /home/marcobraga/.go/src/github.com/mtulio/rundeck-exporter/cmd/rundeck-exporter/init.go:125 +0x5c
azion_1  | main.init.0()
azion_1  |      /home/marcobraga/.go/src/github.com/mtulio/rundeck-exporter/cmd/rundeck-exporter/init.go:115 +0x4ec
monitor_azion_1 exited with code 2
```

Regards,
Thomas

**Comment by mtulio** [comment]
Hello @thomas-illiet , 

Thanks for your feedback and report.

I just create an RC [v0.1.5-rc1 ](https://github.com/mtulio/rundeck-exporter/releases/tag/v0.1.5-rc1), could you please validate if it will help you?

I just add the option `-no-verify-ssl` on #11.

`export RUNDECK_API_URL=https://my-rundeck.url; ./bin/rundeck-exporter -rundeck.user $RUN_USER -rundeck.pass $RUN_PASS -no-verify-ssl `

**Comment by thomas-illiet** [comment]
Thank you for this contribution, but unfortunately I haven't finished my mission at my client, so I can't test your product :/
